#!/bin/bash
# Setting tilix as default terminal
# sudo update-alternatives --config x-terminal-emulator
# chose number

# Setting flameshot /usr/bin/flameshot gui
# Set gnome tweaks
# - hoover
# Set configs from my github
# Dropbox
# Oh my bash
# Settings:
# pl keyboard, 24h time, night mode
