#!/bin/bash
# Minimal install
# before running this script run first "minimal" or doas

# Update repos and OS
doas -- apt update -y && doas -- apt upgrade -y

# Drivers for Intel CPU
doas -- apt install intel-microcode -y

# Minimal programs and X11
doas -- apt install git rxvt-unicode vim xorg xserver-xorg -y

# Minimal regular programs
doas -- apt install python3 python3-pip python-gobject python-dbus libpangocairo-1.0-0 alsa-utils pavucontrol firefox-esr suckless-tools ranger tilix feh compton rofi -y

# Dependencies for Qtile
pip3 install xcffib -y && pip3 install --no-cache-dir cairocffi -y

# Qtile
git clone git://github.com/qtile/qtile.git
cd qtile
pip3 install .

echo "compton &" >> ~/.xinitrc
echo "qtile start" >> ~/.xinitrc
